### ISSUE TITLE
Lattest deb package now has php pgsql dependency

### ISSUE THREAD

**Issue by brendan-pike** [passbolt/passbolt_packaging#2]
Long time user but unable to upgrade to last release because of this issue as I don't use postgres.  ie.
`$ sudo apt install passbolt-ce-server`
now results in 
`The following packages have unmet dependencies:
 passbolt-ce-server : Depends: php-pgsql`
I tried to meet the dependency but it got messy;
```
$ sudo apt install php-pgsql
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php8.1-pgsql : Depends: php8.1-common (= 8.1.2-1ubuntu2.14) but 8.1.20-1+ubuntu20.04.1+deb.sury.org+1 is to be installed
E: Unable to correct problems, you have held broken packages.
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

**Comment by dlen** [comment]
Hi @brendan-pike,

If I understand it correctly you are using ondrej php ppa, right?

**Comment by brendan-pike** [comment]
Hi @dlen 
Thanks for your query, after that I realised I had left the ondrej php ppa apt source commented out after a distro upgrade. Once I removed the comment everything was working fine again and it upgraded without issue.
My bad :)
